import jsPDF from 'jspdf'
import html2canvas from 'html2canvas'
import { AnalysisData } from '../types'

export async function generateReport(data: AnalysisData) {
  // Create a temporary div to render the report
  const reportDiv = document.createElement('div')
  reportDiv.style.width = '210mm'
  reportDiv.style.padding = '20mm'
  reportDiv.style.backgroundColor = 'white'
  reportDiv.style.fontFamily = 'Arial, sans-serif'
  
  reportDiv.innerHTML = generateReportHTML(data)
  document.body.appendChild(reportDiv)
  
  try {
    const canvas = await html2canvas(reportDiv, {
      scale: 2,
      useCORS: true,
      logging: false,
    })
    
    const imgData = canvas.toDataURL('image/png')
    const pdf = new jsPDF('p', 'mm', 'a4')
    
    const imgWidth = 210
    const pageHeight = 297
    const imgHeight = (canvas.height * imgWidth) / canvas.width
    let heightLeft = imgHeight
    
    let position = 0
    
    pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight)
    heightLeft -= pageHeight
    
    while (heightLeft >= 0) {
      position = heightLeft - imgHeight
      pdf.addPage()
      pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight)
      heightLeft -= pageHeight
    }
    
    pdf.save(`InsightBox_Report_${data.fileName.replace(/\.[^/.]+$/, '')}.pdf`)
  } catch (error) {
    console.error('Error generating PDF:', error)
    alert('Error generating PDF report. Please try again.')
  } finally {
    document.body.removeChild(reportDiv)
  }
}

function generateReportHTML(data: AnalysisData): string {
  return `
    <div style="color: #333; line-height: 1.6;">
      <h1 style="color: #003478; border-bottom: 3px solid #FFD100; padding-bottom: 10px;">
        InsightBox Analysis Report
      </h1>
      
      <div style="margin: 20px 0; padding: 15px; background: #f8f9fa; border-left: 4px solid #0066CC;">
        <h2 style="margin-top: 0; color: #003478;">Dataset Information</h2>
        <p><strong>File:</strong> ${data.fileName}</p>
        <p><strong>Analyzed:</strong> ${data.uploadedAt.toLocaleString()}</p>
        <p><strong>Dimensions:</strong> ${data.eda.shape.rows.toLocaleString()} rows × ${data.eda.shape.columns} columns</p>
      </div>
      
      <h2 style="color: #003478; margin-top: 30px;">Executive Summary</h2>
      <div style="margin: 15px 0;">
        <h3 style="color: #0066CC;">Key Insights</h3>
        <ul>
          ${data.eda.insights.map(insight => `<li>${insight}</li>`).join('')}
        </ul>
      </div>
      
      <div style="margin: 15px 0;">
        <h3 style="color: #0066CC;">Recommendations</h3>
        <ul>
          ${data.eda.recommendations.map(rec => `<li>${rec}</li>`).join('')}
        </ul>
      </div>
      
      ${data.efa ? `
        <h2 style="color: #003478; margin-top: 30px;">Factor Analysis Results</h2>
        <div style="margin: 15px 0; padding: 15px; background: #f0f0f0;">
          <p><strong>Factors Extracted:</strong> ${data.efa.factorAnalysis.factors}</p>
          <p><strong>Variance Explained:</strong> ${data.efa.factorAnalysis.cumulativeVariance[data.efa.factorAnalysis.cumulativeVariance.length - 1].toFixed(1)}%</p>
          <p><strong>Suitability:</strong> ${data.efa.suitability.message}</p>
        </div>
      ` : ''}
      
      <h2 style="color: #003478; margin-top: 30px;">Column Statistics</h2>
      <table style="width: 100%; border-collapse: collapse; margin: 15px 0;">
        <thead>
          <tr style="background: #003478; color: white;">
            <th style="padding: 10px; text-align: left;">Column</th>
            <th style="padding: 10px; text-align: left;">Type</th>
            <th style="padding: 10px; text-align: left;">Missing</th>
            <th style="padding: 10px; text-align: left;">Mean</th>
            <th style="padding: 10px; text-align: left;">Std Dev</th>
          </tr>
        </thead>
        <tbody>
          ${data.eda.columns.map((col, idx) => `
            <tr style="border-bottom: 1px solid #ddd; ${idx % 2 === 0 ? 'background: #f9f9f9;' : ''}">
              <td style="padding: 8px;">${col.name}</td>
              <td style="padding: 8px;">${col.type}</td>
              <td style="padding: 8px;">${col.missingPercent.toFixed(1)}%</td>
              <td style="padding: 8px;">${col.mean !== undefined ? col.mean.toFixed(2) : '-'}</td>
              <td style="padding: 8px;">${col.std !== undefined ? col.std.toFixed(2) : '-'}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>
      
      <div style="margin-top: 30px; padding-top: 20px; border-top: 2px solid #ddd; text-align: center; color: #666; font-size: 12px;">
        <p>Generated by InsightBox - The Cursor of EDA/EFA</p>
        <p>Democratizing data insights for everyone</p>
      </div>
    </div>
  `
}

